/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employees;

import java.awt.Color;

/**
 *
 * @author Sbani
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
//        setDefaultLookAndFeelDecorated(true);
        
        initComponents();
        
//        getContentPane();
//        setUndecorated(true);
//        setOpacity(0.0f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mangeRoom = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        bookRoom = new javax.swing.JButton();
        viewBookedRooms = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sbani");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mangeRoom.setBackground(new java.awt.Color(0, 0, 0));
        mangeRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mangeRoom.setForeground(new java.awt.Color(255, 255, 255));
        mangeRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mange.png"))); // NOI18N
        mangeRoom.setText("Manage Rooms");
        mangeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeRoomActionPerformed(evt);
            }
        });
        getContentPane().add(mangeRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 102, 214, 121));

        checkIn.setBackground(new java.awt.Color(0, 0, 0));
        checkIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkIn.setForeground(new java.awt.Color(255, 255, 255));
        checkIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checkin.png"))); // NOI18N
        checkIn.setText("Check In");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });
        getContentPane().add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 102, 214, 121));

        checkOut.setBackground(new java.awt.Color(0, 0, 0));
        checkOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOut.setForeground(new java.awt.Color(255, 255, 255));
        checkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checkout.png"))); // NOI18N
        checkOut.setText("Check Out");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 102, 214, 121));

        bookRoom.setBackground(new java.awt.Color(0, 0, 0));
        bookRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookRoom.setForeground(new java.awt.Color(255, 255, 255));
        bookRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book.png"))); // NOI18N
        bookRoom.setText("Book Room");
        getContentPane().add(bookRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 319, 214, 121));

        viewBookedRooms.setBackground(new java.awt.Color(0, 0, 0));
        viewBookedRooms.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewBookedRooms.setForeground(new java.awt.Color(255, 255, 255));
        viewBookedRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view.png"))); // NOI18N
        viewBookedRooms.setText("View Bookings");
        viewBookedRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookedRoomsActionPerformed(evt);
            }
        });
        getContentPane().add(viewBookedRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 319, 214, 121));

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 319, 214, 121));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1001, 517));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 560));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutActionPerformed

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInActionPerformed

    private void mangeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mangeRoomActionPerformed

    private void viewBookedRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookedRoomsActionPerformed
        // TODO add your handling code here:
        BookedRooms booked=new BookedRooms();
        booked.setVisible(true);
        booked.setLocationRelativeTo(null);
    }//GEN-LAST:event_viewBookedRoomsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                Home home=new Home();
              
                home.setLocationRelativeTo(null);
//                home.setUndecorated(false);
//                home.setBackground(Color.yellow);
                home.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookRoom;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton mangeRoom;
    private javax.swing.JButton viewBookedRooms;
    // End of variables declaration//GEN-END:variables
}
